# Generated by Django 5.2.4 on 2025-07-04 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Course Title')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='student.student', verbose_name='Students')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
        ),
    ]
