# Generated by Django 5.2.4 on 2025-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=40, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.IntegerField(default=1000, verbose_name='Course Fee(BDT)'),
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(default='sat-mon-wed', help_text='e.g. sat/mon/wed', max_length=30, verbose_name='Days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default='4 PM', help_text='e.g. 4 PM', max_length=20, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
