# Generated by Django 5.2.4 on 2025-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_capacity_course_course_fee_course_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_quote',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Quote'),
        ),
    ]
