# Generated by Django 5.2.4 on 2025-07-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('guardian_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Guardian Name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('guardian_contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Guardian Contact Number')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
